/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorRouteImport } from './routes/author'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallForPapersIndexRouteImport } from './routes/call-for-papers/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLogoutRouteImport } from './routes/auth/logout'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthConfirmEmailSentRouteImport } from './routes/auth/confirm-email-sent'
import { Route as AuthConfirmEmailRouteImport } from './routes/auth/confirm-email'
import { Route as CallForPapersAcronymIndexRouteImport } from './routes/call-for-papers/$acronym/index'
import { Route as CallForPapersAcronymSubmissionNumberRouteImport } from './routes/call-for-papers/$acronym/submission/$number'

const AuthorRoute = AuthorRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallForPapersIndexRoute = CallForPapersIndexRouteImport.update({
  id: '/call-for-papers/',
  path: '/call-for-papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailSentRoute = AuthConfirmEmailSentRouteImport.update({
  id: '/confirm-email-sent',
  path: '/confirm-email-sent',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConfirmEmailRoute = AuthConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => AuthRoute,
} as any)
const CallForPapersAcronymIndexRoute =
  CallForPapersAcronymIndexRouteImport.update({
    id: '/call-for-papers/$acronym/',
    path: '/call-for-papers/$acronym/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CallForPapersAcronymSubmissionNumberRoute =
  CallForPapersAcronymSubmissionNumberRouteImport.update({
    id: '/call-for-papers/$acronym/submission/$number',
    path: '/call-for-papers/$acronym/submission/$number',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/author': typeof AuthorRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-email-sent': typeof AuthConfirmEmailSentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/call-for-papers': typeof CallForPapersIndexRoute
  '/call-for-papers/$acronym': typeof CallForPapersAcronymIndexRoute
  '/call-for-papers/$acronym/submission/$number': typeof CallForPapersAcronymSubmissionNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/author': typeof AuthorRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-email-sent': typeof AuthConfirmEmailSentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/call-for-papers': typeof CallForPapersIndexRoute
  '/call-for-papers/$acronym': typeof CallForPapersAcronymIndexRoute
  '/call-for-papers/$acronym/submission/$number': typeof CallForPapersAcronymSubmissionNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/author': typeof AuthorRoute
  '/auth/confirm-email': typeof AuthConfirmEmailRoute
  '/auth/confirm-email-sent': typeof AuthConfirmEmailSentRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/register': typeof AuthRegisterRoute
  '/call-for-papers/': typeof CallForPapersIndexRoute
  '/call-for-papers/$acronym/': typeof CallForPapersAcronymIndexRoute
  '/call-for-papers/$acronym/submission/$number': typeof CallForPapersAcronymSubmissionNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/author'
    | '/auth/confirm-email'
    | '/auth/confirm-email-sent'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/call-for-papers'
    | '/call-for-papers/$acronym'
    | '/call-for-papers/$acronym/submission/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/author'
    | '/auth/confirm-email'
    | '/auth/confirm-email-sent'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/call-for-papers'
    | '/call-for-papers/$acronym'
    | '/call-for-papers/$acronym/submission/$number'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/author'
    | '/auth/confirm-email'
    | '/auth/confirm-email-sent'
    | '/auth/login'
    | '/auth/logout'
    | '/auth/register'
    | '/call-for-papers/'
    | '/call-for-papers/$acronym/'
    | '/call-for-papers/$acronym/submission/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthorRoute: typeof AuthorRoute
  CallForPapersIndexRoute: typeof CallForPapersIndexRoute
  CallForPapersAcronymIndexRoute: typeof CallForPapersAcronymIndexRoute
  CallForPapersAcronymSubmissionNumberRoute: typeof CallForPapersAcronymSubmissionNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-for-papers/': {
      id: '/call-for-papers/'
      path: '/call-for-papers'
      fullPath: '/call-for-papers'
      preLoaderRoute: typeof CallForPapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email-sent': {
      id: '/auth/confirm-email-sent'
      path: '/confirm-email-sent'
      fullPath: '/auth/confirm-email-sent'
      preLoaderRoute: typeof AuthConfirmEmailSentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/confirm-email': {
      id: '/auth/confirm-email'
      path: '/confirm-email'
      fullPath: '/auth/confirm-email'
      preLoaderRoute: typeof AuthConfirmEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/call-for-papers/$acronym/': {
      id: '/call-for-papers/$acronym/'
      path: '/call-for-papers/$acronym'
      fullPath: '/call-for-papers/$acronym'
      preLoaderRoute: typeof CallForPapersAcronymIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-for-papers/$acronym/submission/$number': {
      id: '/call-for-papers/$acronym/submission/$number'
      path: '/call-for-papers/$acronym/submission/$number'
      fullPath: '/call-for-papers/$acronym/submission/$number'
      preLoaderRoute: typeof CallForPapersAcronymSubmissionNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthConfirmEmailRoute: typeof AuthConfirmEmailRoute
  AuthConfirmEmailSentRoute: typeof AuthConfirmEmailSentRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmEmailRoute: AuthConfirmEmailRoute,
  AuthConfirmEmailSentRoute: AuthConfirmEmailSentRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthorRoute: AuthorRoute,
  CallForPapersIndexRoute: CallForPapersIndexRoute,
  CallForPapersAcronymIndexRoute: CallForPapersAcronymIndexRoute,
  CallForPapersAcronymSubmissionNumberRoute:
    CallForPapersAcronymSubmissionNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
